### ISSUE TITLE
Missing contains_keys_in_range and get_in_range

### ISSUE THREAD

**Issue by juliotpaez** [jeffparsons/rangemap#23]
Hello,

I've just discovered your crate and it suits all my needs but one. I need to know whether the maps (in my case) contains any key in a provided range.

For example:

```rust
let mut map = RangeMap::new();

// Fill map.
map.insert(10..20, "a");
map.insert(50..70, "b");

// Checks.
map.contains_keys_in_range(5..9); // false
map.contains_keys_in_range(5..35); // true
map.contains_kesy_in_range(20..45); // false
```

Also, it would be very useful to retrieve all elements that collide with the range:

```rust
let mut map = RangeMap::new();

// Fill map.
map.insert(10..20, "a");
map.insert(50..70, "b");

// Get.
map.get_in_range(5..9); // []
map.get_in_range(5..35); // ["a"]
map.get_in_range(20..45); // []
```

> Note: feel free to change the method names.

**Comment by Rua** [comment]
I came here looking for the same thing. Can this be added?

**Comment by jeffparsons** [comment]
Closing this now that https://github.com/jeffparsons/rangemap/pull/59 and https://github.com/jeffparsons/rangemap/pull/61 have been merged.
