### ISSUE TITLE
Add missing methods

### ISSUE THREAD

**Issue by jeffparsons** [jeffparsons/rangemap#3]
- [x] `remove`
- [ ] Equivalents of anything from https://doc.rust-lang.org/std/collections/struct.BTreeMap.html that sounds useful

**Comment by penberg** [comment]
`get_key_value` would be a really useful addition to the interface so I would be able to determine the start and end of the key range upon value lookup.

**Comment by jeffparsons** [comment]
@penberg I've added `get_key_value` to `RangeMap` and `RangeSet` and cut a new release. Just published it a couple of minutes ago, so it might take a while to show up on docs.rs, etc.

**Comment by jeffparsons** [comment]
Closing this because there's nothing specific left on the list. We can open new tickets for specific methods as they come up.
