### ISSUE TITLE
License files should be included in the repository

### ISSUE THREAD

**Issue by acully-vmware** [jeffparsons/rangemap#37]
The `Cargo.toml` lists this as licensed under both MIT and Apache-2.0 terms, but only `LICENSE-MIT` is included in the repository. Can either the Cargo.toml be updated, or else add a `LICENSE-APACHE` file?

**Comment by jeffparsons** [comment]
I've added the `LICENSE-APACHE` file: https://github.com/jeffparsons/rangemap/commit/83126e55823e167e13c2a68e7a1971d724664d44

Thanks for pointing this out! :blush:
