### ISSUE TITLE
Implement PartialEq and Eq for RangeMap

### ISSUE THREAD

**Issue by mstange** [jeffparsons/rangemap#51]
`RangeMap` currently does not implement `Eq` or `PartialEq`, even if the keys and values stored in it implement those traits.

It would be nice if these traits were implemented. One thing this allows would be to store RangeMaps inside RangeMaps.

My use case is the following:

```rust
struct SymbolFile {
    functions: RangeMap<u64, Function>,
}

struct Function {
    name: String,
    lines: RangeMap<u64, SourceLine>,
}
```

This currently doesn't work because you can't `#[derive(Eq)]` on `Function` due to the `RangeMap` inside it.

**Comment by jeffparsons** [comment]
Closed via https://github.com/jeffparsons/rangemap/pull/54

Will be in a release soon.

**Comment by mstange** [comment]
Thanks!
