### ISSUE TITLE
`rangemap!` macro

### ISSUE THREAD

**Issue by k12ish** [jeffparsons/rangemap#66]
Thank you for maintaining this library!

I tried to create a literal `RangeMap` using this example:

```rust
use std::collections::{BTreeMap, BTreeSet, HashMap, HashSet};

macro_rules! collection {
    // map-like
    ($($k:expr => $v:expr),* $(,)?) => {{
        core::convert::From::from([$(($k, $v),)*])
    }};
    // set-like
    ($($v:expr),* $(,)?) => {{
        core::convert::From::from([$($v,)*])
    }};
}

fn main() {
    let s: BTreeSet<_> = collection! { 1, 2, 3 };
    println!("{:?}", s);

    let s: BTreeMap<_, _> = collection! { 1 => 2, 3 => 4 };
    println!("{:?}", s);
}
```

Unfortunately, the same trick does not work for `RangeMap` or `RangeSet`:

```
54 |         core::convert::From::from([$(($k, $v),)*])
   |         ------------------------- ^^^^^^^^^^^^^^^ the trait `From<[(std::ops::Range<usize>, Color); 1]>` is not implemented for `RangeMap<usize, Color>`
```

If you decide that you want to implement a `rangemap!` macro similar to `vec!`, `smallvec!`, I reccommend that you:

- Implement `From<[Range<K>, V; N]>` for `Range*` types 
- Implement and export corresponding macros

I understand that you may be busy, so I may be able to help with implementing this feature.

## Alternatives for the end user

In the meanwhile, this code works for me:

```rust
macro_rules! rangemap_lit {
    ($($k:expr => $v:expr),* $(,)?) => {{
        RangeMap::from_iter([$(($k, $v),)*])
    }};
}
```

**Comment by xfbs** [comment]
@jeffparsons I think this issue can be closed, it was addressed in #83.
