### ISSUE TITLE
Getting the last range of the collection, like `BTMap::last_key_value`

### ISSUE THREAD

**Issue by urben1680** [jeffparsons/rangemap#74]
I want to find out what the last range of a `(Inclusive)RangeMap` is, but unlike `BTMap` these structs are missing such a method.

The `Iter` struct also does not implement `DoubleEndedIterator` so I cannot call `rev` and `next` to get the desired information.

**Comment by jeffparsons** [comment]
`first`/`last` and making the iterator double-ended both sound useful. Would you be interested in implementing either or both? (I'm very time-constrained right now.)
