### ISSUE TITLE
intersection for RangeSet and RangeInclusiveSet

### ISSUE THREAD

**Issue by xfbs** [jeffparsons/rangemap#75]
This is a really awesome crate, thank you very much for implementing it!

I have a use-case where I would like to get the intersection of two `RangeInclusiveSet`. I think this could be done somewhat efficiently.

**Comment by jeffparsons** [comment]
> This is a really awesome crate, thank you very much for implementing it!

💖

> I have a use-case where I would like to get the intersection of two `RangeInclusiveSet`. I think this could be done somewhat efficiently.

Yep, that sounds useful. I don't have time to add this right now, but you're welcome to have a go. If you don't already have an implementation strategy in mind, I imagined something like:

- Iterate over both sets concurrently, reinterpreting ranges as "start" and "end" events.
- Track "how many ranges am I currently inside". Or just two separate bools for "in a range from a" and "in a range from b" I guess?
- Pop off whatever event comes next, _and_ any others for the same value.
- If you're now inside two ranges, start a range to eventually yield from the iterator.
- If you were inside two ranges but now you're not, yield the range.

Does that make some kind of sense?

**Comment by xfbs** [comment]
I think that kind of makes sense! I think I had a similar idea. Basically keep two iterators, and alternate between pulling from either one and merging the ranges. I'm gonna draft up something and send a PR your way if I get anything useful :)

**Comment by xfbs** [comment]
I've created a PR for this, #80. Have a look at it and see if it makes sense to you!
