### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by xfbs** [jeffparsons/rangemap#89]
Currently, the CI system is broken (perhaps due to a new dependency?). We should get this fixed, I think bumping the MSRV to 1.63 should do the trick.

**Comment by jeffparsons** [comment]
I bumped the MSRV; we only need 1.66, which is over a year old. In lieu of a proper MSRV policy, that seems plenty generous.

That said, we should probably have a look at what other crates do and publish a policy. We can easily support more than "last two releases", bit
