### ISSUE TITLE
Implement quickcheck::Arbitrary for rangemap::RangeSet?

### ISSUE THREAD

**Issue by schneiderfelipe** [jeffparsons/rangemap#98]
It would be nice to have this crate compatible with [quickcheck](https://github.com/BurntSushi/quickcheck).

**Comment by jeffparsons** [comment]
I'm open to this. 👍

I would want it to be gated behind a "quickcheck" feature, so that quickcheck is an optional dependency.

**Comment by jeffparsons** [comment]
Released 1.6.0 to crates.io.
